# variables for the pt fit (used in the ptFit macro)
  # edges of the bins used in the pT fit, the width of the bins can be bin-dependent
  ptFitBinning: [0.00, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10,
                 0.11, 0.12, 0.13, 0.14, 0.15, 0.175, 0.20, 0.25, 0.30, 0.40, 0.50,
                 0.60, 0.70, 0.80, 0.90, 1.00, 1.20, 1.40, 1.60, 1.80, 2.00, 2.50,
                 3.00, 3.50]

  # to have nPtBins equally spaced in the range [lowPt, upPt] please specify
  # the values here, leaving ptFitBinning as an empty list (or deleting it)
  # Note: if ptFitBinning is not empty the values below are ignored and set
  #       to the values from ptFitBinning
  lowPt: 0
  upPt: 2
  nPtBins: 200

  # flag true to use a MC tamplate for yy->mumu processes
  # flag false to fit the mass distribution and fit the number of jpsi vs pT
  useContinuumTemplate: true

  # if using the template for continuum yy->mumu it is possible to do
  # an unbinned fit
  # Note: not available for now! It will always been set to true
  binnedFit: true

  # if the fit is binned it is possible to do the fit using the chi2
  chi2Fit: true

  # mass range used in the pT fit (for both data and MC if not doing a mass fit)
  massRange_ptFit: [2.85, 3.35]

  # rapidity range, valid also for the mass fits
  rapidityRange: [-4, -2.5]

# variables set for the mass fit
  # mass range used in the mass fit
  'massRange_massFit': [2, 4]
  
  
